// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egluycabmxfpnodlrvnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnbHV5Y2FibXhmcG5vZGxydm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2Nzk0MDUsImV4cCI6MjA4NTI1NTQwNX0.x9xRDWzO7YSmyBjS9WfsihI8nDnHOr08WQngqmdU4cE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});